-- ============================================================================
-- VEXIM OPS — SEED DỮ LIỆU THAM CHIẾU (chạy sau migrations 0001→0003)
-- Nội dung: 10 SOP template còn lại (0002 đã seed SOP-01, SOP-04)
-- Nguồn bước: docs/luong-van-hanh-chuan.md — VEXIM chỉnh được sau.
-- Idempotent: chạy nhiều lần không lỗi (ON CONFLICT DO NOTHING).
-- ============================================================================

insert into ops.task_templates (sop_code, name, department_id, trigger_rule, sla_hours, steps) values
('SOP-02', 'Giữ/lấy lại Featured Offer (Buy Box)',
 (select id from iam.departments where code='fulfillment'), 'buybox_lost', 4,
 '[{"n":1,"name":"Xác nhận mất box thật (2 lần cách 30 phút)","who":"Hệ thống","data":"Pricing API"},
   {"n":2,"name":"Phân tích giá đối thủ","who":"Hệ thống","data":"ANY_OFFER_CHANGED"},
   {"n":3,"name":"Tính giá sàn (vốn + phí Amazon + biên tối thiểu)","who":"Hệ thống","data":"Product Fees API"},
   {"n":4,"name":"Rẽ nhánh: đua giá hay đổi chiến lược","who":"Kho vận","data":"quy tắc"},
   {"n":5,"name":"Duyệt giá theo ngưỡng %","who":"Operator/Trưởng phòng","data":"màn duyệt"},
   {"n":6,"name":"Cập nhật giá","who":"Hệ thống","data":"patchListingsItem (purchasable_offer)"},
   {"n":7,"name":"Xác nhận lấy lại box + ghi precedent","who":"Kho vận","data":"Pricing API"}]'::jsonb),
('SOP-03', 'Khôi phục listing inactive/stranded',
 (select id from iam.departments where code='listing'), 'listing_inactive', 24,
 '[{"n":1,"name":"Xác định nguyên nhân (issues list)","who":"Hệ thống","data":"Listings Items API"},
   {"n":2,"name":"Soạn bản sửa (draft)","who":"Listing","data":"checklist nội bộ"},
   {"n":3,"name":"Trưởng phòng duyệt nội dung","who":"Trưởng phòng Listing","data":"màn duyệt"},
   {"n":4,"name":"Publish lên Amazon","who":"Hệ thống","data":"patchListingsItem"},
   {"n":5,"name":"Theo dõi 24h xác nhận active","who":"Hệ thống","data":"LISTINGS_ITEM_STATUS_CHANGE"},
   {"n":6,"name":"Stranded do tồn → phối Kho vận","who":"Listing + Kho vận","data":""},
   {"n":7,"name":"Lỗi lặp → cập nhật checklist","who":"Trưởng phòng","data":""}]'::jsonb),
('SOP-05', 'Campaign hết budget sớm',
 (select id from iam.departments where code='ppc'), 'budget_exhausted', 6,
 '[{"n":1,"name":"Xác nhận budget cạn trước 18h hôm trước","who":"Hệ thống","data":"Ads metrics"},
   {"n":2,"name":"Xem hiệu quả 7 ngày của campaign","who":"PPC","data":"Reporting v3"},
   {"n":3,"name":"Tốt → đề xuất tăng budget · Xấu → chuyển SOP-04","who":"PPC","data":""},
   {"n":4,"name":"Duyệt (tăng >30%/ngày cần trưởng phòng)","who":"theo ngưỡng","data":"màn duyệt"},
   {"n":5,"name":"Áp dụng + theo dõi chiều cùng ngày","who":"Hệ thống + PPC","data":"Ads API"}]'::jsonb),
('SOP-06', 'Đơn FBM + tin nhắn người mua',
 (select id from iam.departments where code='orders_care'), 'message_aging', 24,
 '[{"n":1,"name":"Xác nhận đơn FBM theo thứ tự hạn","who":"CSKH","data":"Orders API + ORDER_CHANGE"},
   {"n":2,"name":"Gửi vận đơn / cập nhật tracking","who":"CSKH + hệ thống","data":"tracking live"},
   {"n":3,"name":"Trả lời tin nhắn theo template","who":"CSKH","data":"log nội bộ (SP-API không đọc hộp thư)"},
   {"n":4,"name":"Khó → escalation trưởng phòng","who":"Trưởng phòng CSKH","data":""},
   {"n":5,"name":"Theo dõi ODR/LSR/VTR vs ngưỡng","who":"Hệ thống","data":"Seller Performance Report"}]'::jsonb),
('SOP-07', 'Feedback/Review xấu mới',
 (select id from iam.departments where code='orders_care'), null, 4,
 '[{"n":1,"name":"Phân loại nguyên nhân","who":"CSKH","data":""},
   {"n":2,"name":"Vi phạm chính sách → yêu cầu gỡ","who":"CSKH","data":"Seller Central"},
   {"n":3,"name":"Liên hệ giải quyết buyer","who":"CSKH","data":""},
   {"n":4,"name":"Lỗi lặp ≥2 lần → task phòng Listing","who":"Trưởng phòng CSKH","data":""},
   {"n":5,"name":"Ghi note + theo dõi chỉ số feedback","who":"CSKH","data":""}]'::jsonb),
('SOP-08', 'Account Health rớt / vi phạm mới',
 (select id from iam.departments where code='ops_health'), 'account_health', 24,
 '[{"n":1,"name":"Đọc chi tiết vi phạm + mức nghiêm trọng","who":"Vận hành","data":"GET_V1_SELLER_PERFORMANCE_REPORT"},
   {"n":2,"name":"Phân loại: IP · hạn chế · chất lượng · hiệu suất","who":"Vận hành","data":""},
   {"n":3,"name":"Thu thập bằng chứng","who":"Vận hành + phòng liên quan","data":"hồ sơ nội bộ"},
   {"n":4,"name":"Nộp appeal trên Seller Central","who":"Vận hành","data":"Seller Central"},
   {"n":5,"name":"Theo dõi case — đẩy mỗi 48h","who":"Vận hành","data":""},
   {"n":6,"name":"Post-mortem + thêm alert phòng ngừa","who":"Trưởng phòng","data":"alert_rules"}]'::jsonb),
('SOP-09', 'Claim bồi hoàn FBA',
 (select id from iam.departments where code='finance'), null, 72,
 '[{"n":1,"name":"Đối chiếu tồn báo cáo vs thực nhận từng lô","who":"Tài chính","data":"FBA reports"},
   {"n":2,"name":"Phân loại khoản nghi ngờ","who":"Tài chính","data":""},
   {"n":3,"name":"Ước tính giá trị từng khoản","who":"Tài chính","data":"cost_inputs"},
   {"n":4,"name":"Nộp case Seller Central + bằng chứng","who":"Tài chính","data":"Seller Central"},
   {"n":5,"name":"Theo dõi case (48h không phản hồi thì đẩy)","who":"Tài chính","data":""},
   {"n":6,"name":"Ghi nhận tiền về","who":"Hệ thống","data":"GET_FBA_REIMBURSEMENTS_DATA"},
   {"n":7,"name":"Tổng hợp vào báo cáo khách hàng tuần","who":"Tài chính","data":"SOP-12"}]'::jsonb),
('SOP-10', 'Đối soát kỳ settlement hằng ngày',
 (select id from iam.departments where code='finance'), null, 4,
 '[{"n":1,"name":"Kéo settlement + All Orders của ngày trước","who":"Hệ thống (pg_cron)","data":"Reports API"},
   {"n":2,"name":"Đối chiếu 3 nguồn: hệ thống vs settlement vs Seller Central","who":"Hệ thống","data":""},
   {"n":3,"name":"Đánh dấu lệch > 1% để điều tra","who":"Tài chính","data":""},
   {"n":4,"name":"Lỗi hệ thống → sửa pipeline · Lỗi Amazon → mở case","who":"Dev / Tài chính","data":""},
   {"n":5,"name":"Chốt kpi_daily — 6h sáng dashboard có số chuẩn","who":"Hệ thống","data":"kpi_daily"}]'::jsonb),
('SOP-11', 'Kết nối shop mới (onboarding)',
 (select id from iam.departments where code='ops_health'), null, 48,
 '[{"n":1,"name":"Gửi link Kết nối Amazon cho chủ shop","who":"Vận hành","data":"OAuth LWA"},
   {"n":2,"name":"Seller authorize","who":"Khách hàng","data":"Seller Central"},
   {"n":3,"name":"Backfill 30 ngày + đăng ký notifications","who":"Hệ thống","data":"SP-API"},
   {"n":4,"name":"Nhập giá vốn, lead time, ngưỡng cảnh báo","who":"Vận hành + Khách hàng","data":"cost_inputs"},
   {"n":5,"name":"Gán phòng ban/nhân viên phụ trách","who":"Trưởng phòng","data":"iam.assignments"},
   {"n":6,"name":"Smoke test 8 dashboard + rà 12 SOP","who":"Vận hành","data":""},
   {"n":7,"name":"Bàn giao vận hành chính thức","who":"Vận hành","data":""}]'::jsonb),
('SOP-12', 'Báo cáo khách hàng tuần',
 (select id from iam.departments where code='ops_health'), null, 4,
 '[{"n":1,"name":"Tự sinh báo cáo từ kpi_daily","who":"Hệ thống","data":"kpi_daily"},
   {"n":2,"name":"Trưởng phòng kiểm duyệt","who":"Trưởng phòng","data":""},
   {"n":3,"name":"Gửi email khách + lưu hệ thống","who":"Hệ thống","data":"ops.client_reports"},
   {"n":4,"name":"Ghi nhận phản hồi của khách vào tuần sau","who":"Vận hành","data":""}]'::jsonb)
on conflict (sop_code) do nothing;
